docker-deploy/docker-deploy/web-app/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views
from driverRegister import views as driver_views

app_name = 'accounts'

urlpatterns = [
    url(r'login/$',auth_views.LoginView.as_view(template_name='accounts/login.html'),
    name='login'),
    url(r'logout/$',auth_views.LogoutView.as_view(),name='logout'),
    url(r'signup/$',views.SignUp.as_view(),name='signup')
    #url(r'^profile/$',driver_views.views.profile, name='profile')
]

docker-deploy/docker-deploy/web-app/driverRegister/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views
from django import forms
from django.forms import ModelForm

app_name = 'driverRegister'

urlpatterns = [
    url(r'^$',views.reg_driver,name='registerdriver'),
    url(r'^profile/$',views.view_profile, name='view_profile'),
    url(r'^profile/edit/$',views.edit_profile, name='edit_profile'),
    url(r'^profile/edit/personal/$',views.edit_profile_personal, name='edit_profile_personal')
]

docker-deploy/docker-deploy/web-app/rideRequest/urls.py
from django.conf.urls import url
from . import views

app_name = 'rideRequest'

urlpatterns = [
    url(r'^$',views.request_ride,name='requestride'),
    url(r'^personalrequest/$',views.personal_request,name='personalrequest'),
    url(r'^driversearch/$',views.driver_search,name='driversearch'),
    url(r'^delete/(?P<part_id>[0-9]+)/$', views.delete_view, name='delete_view'),
    url(r'^accept/(?P<part_id>[0-9]+)/$', views.accept_view, name='accept_view'),
    url(r'^complete/(?P<part_id>[0-9]+)/$', views.complete_view, name='complete_view'),
    url(r'^join/(?P<part_id>[0-9]+)/(?P<num_passengers>[0-9]+)$', views.join_view, name='join_view'),
    url(r'^rideshare/$',views.share_view,name='share_view'),
    url(r'^editride/(?P<part_id>[0-9]+)/$', views.edit_view, name='edit_view'),
    url(r'^confirmedride/$', views.confirmed_view, name='confirmed_view'),
]

docker-deploy/docker-deploy/web-app/ride_share_service/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.HomePage.as_view(),name='home'),
    url(r'^accounts/', include('accounts.urls',namespace='accounts')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^test/$',views.TestPage.as_view(),name='test'),
    url(r'^thanks/$',views.ThanksPage.as_view(),name='thanks'),
    url(r'^registerdriver/', include('driverRegister.urls',namespace='driverregister')),
    url(r'^requestride/', include('rideRequest.urls'))
]

docker-deploy/docker-deploy/web-app/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.HomePage.as_view(),name='home'),
    url(r'^accounts/', include('accounts.urls',namespace='accounts')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^test/$',views.TestPage.as_view(),name='test'),
    url(r'^thanks/$',views.ThanksPage.as_view(),name='thanks'),
    url(r'^registerdriver/', include('driverRegister.urls',namespace='driverregister')),
    url(r'^requestride/', include('rideRequest.urls'))
]

docker-deploy/docker-deploy/web-app/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Ride Share</title>
  </head>
  <body>
    <nav class="navbar mynav" role='navigation' id='navbar'>
      <div class="container">
        <a class="navbar-brand mynav" href="{% url 'home' %}">Ride Share</a>
        <ul class='nav navbar-nav navbar-right'>
          {% if user.is_authenticated %}
            <li><a href="{% url 'driverRegister:registerdriver' %}">Register to become a driver</a></li>
            <li><a href="{% url 'rideRequest:requestride' %}">Request a ride</a></li>
            <li><a href="{% url 'accounts:logout' %}">Log out</a></li>
            <li><a  href="{% url 'driverRegister:view_profile' %}">Profile</a></li>
            <li><a href="{% url 'rideRequest:personalrequest' %}">Your Personal Request</a>
	    <li><a href="{% url 'rideRequest:share_view' %}">Request Share Ride</a>
              {% if user.driver %}
                <li><a href="{% url 'rideRequest:confirmed_view' %}">Your Confirmed Ride</a>
              {% endif %}
          {% else %}
            <li><a href="#"></a><li>
            <li><a href="{% url 'accounts:login' %}">Log In</a></li>
            <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>

    <div class="container mycontent">

    </div>
    {% block content %}

    {% endblock %}
  </body>
</html>

docker-deploy/docker-deploy/web-app/templates/index.html
{% extends "base.html" %}

{% block content %}
    <h1>Welcome to the ride share web!</h1>
{% endblock %}

docker-deploy/docker-deploy/web-app/templates/test.html
{% extends "base.html" %}
{% block content %}
<h1>You are now logged in!</h1>

{% endblock %}

docker-deploy/docker-deploy/web-app/templates/thanks.html
{% extends "base.html" %}
{% block content %}
<h1>Thanks for visiting!</h1>

{% endblock %}