docker-deploy/docker-deploy/web-app/rideRequest/urls.py
from django.conf.urls import url
from . import views

app_name = 'rideRequest'

urlpatterns = [
    url(r'^$',views.request_ride,name='requestride'),
    url(r'^personalrequest/$',views.personal_request,name='personalrequest'),
    url(r'^driversearch/$',views.driver_search,name='driversearch'),
    url(r'^delete/(?P<part_id>[0-9]+)/$', views.delete_view, name='delete_view'),
    url(r'^accept/(?P<part_id>[0-9]+)/$', views.accept_view, name='accept_view'),
    url(r'^complete/(?P<part_id>[0-9]+)/$', views.complete_view, name='complete_view'),
    url(r'^join/(?P<part_id>[0-9]+)/(?P<num_passengers>[0-9]+)$', views.join_view, name='join_view'),
    url(r'^rideshare/$',views.share_view,name='share_view'),
    url(r'^editride/(?P<part_id>[0-9]+)/$', views.edit_view, name='edit_view'),
    url(r'^confirmedride/$', views.confirmed_view, name='confirmed_view'),
]

docker-deploy/docker-deploy/web-app/ride_share_service/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.HomePage.as_view(),name='home'),
    url(r'^accounts/', include('accounts.urls',namespace='accounts')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^test/$',views.TestPage.as_view(),name='test'),
    url(r'^thanks/$',views.ThanksPage.as_view(),name='thanks'),
    url(r'^registerdriver/', include('driverRegister.urls',namespace='driverregister')),
    url(r'^requestride/', include('rideRequest.urls'))
]

docker-deploy/docker-deploy/web-app/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.HomePage.as_view(),name='home'),
    url(r'^accounts/', include('accounts.urls',namespace='accounts')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^test/$',views.TestPage.as_view(),name='test'),
    url(r'^thanks/$',views.ThanksPage.as_view(),name='thanks'),
    url(r'^registerdriver/', include('driverRegister.urls',namespace='driverregister')),
    url(r'^requestride/', include('rideRequest.urls'))
]

docker-deploy/docker-deploy/web-app/rideRequest/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from driverRegister.models import Driver
import datetime
#from django_mysql.models import ListTextField
from django.contrib.postgres.fields import ArrayField
# Create your models here.
from django.contrib.auth import get_user_model
User = get_user_model()

class RequestRide(models.Model):
    TYPE_CHOICES = (
    ('1', 'Type1'),
    ('2', 'Type2'),
    ('3', 'Type3'),
    ('4', 'Does not matter')
    )
    #users=[]
    user = models.ForeignKey(User,related_name='request',on_delete=models.CASCADE)
    driver_name = models.CharField(max_length=246, null=True)
    driver_vehicle_type = models.CharField(max_length=246,null=True)
    destination = models.CharField(max_length=246)
    date_time = models.DateField()
    num_passengers = models.IntegerField(validators=[MinValueValidator(1),
                                        MaxValueValidator(5)])
    type = models.CharField(max_length=1,choices=TYPE_CHOICES,default='4')
    special_requests = models.CharField(max_length=300)
    status_share = models.BooleanField(default=False)
    #if the request has been submitted, this status should be set to true
    status_confirm = models.BooleanField(default=False)
    status_conplete = models.BooleanField(default=False)

    remaining_seat = models.IntegerField(default=0,validators=[MinValueValidator(0),
                                        MaxValueValidator(5)])
    join_list = ArrayField(models.CharField(max_length=246), size=4, null=True,default=list)

    def __str__(self):
        return self.user.username

docker-deploy/docker-deploy/web-app/rideRequest/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User
from rideRequest.models import RequestRide
from django.contrib.auth.forms import UserChangeForm
from datetime import date

class RequestForm(forms.ModelForm):
    class Meta:
        model = RequestRide
        fields = ['destination','date_time','num_passengers','type', 'special_requests','status_share']

    def save(self, commit=True):
        user = super(RequestForm,self).save(commit=False)
        user.destination = self.cleaned_data['destination']
        user.date_time = self.cleaned_data['date_time']
        user.num_passengers = self.cleaned_data['num_passengers']
        user.type = self.cleaned_data['type']
        user.special_requests = self.cleaned_data['special_requests']
        user.status_share = self.cleaned_data['status_share']

        if commit:
            user.save()

        return user

docker-deploy/docker-deploy/web-app/rideRequest/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django import forms
from django.forms import ModelForm
from rideRequest.forms import RequestForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from rideRequest.models import RequestRide
from django.contrib import messages
from django.contrib.messages import get_messages
from django.core.mail import send_mail
from django.conf import settings

# Create your views here.
def request_ride(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = RequestForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            instance.save()
            return HttpResponseRedirect(reverse('rideRequest:personalrequest'))
            #return render(request, 'driver_register_form.html', {'form': form,'registered': registered})

    # if a GET (or any other method) we'll create a blank form
    else:
        form = RequestForm()

    return render(request, 'ride_request_detail.html', {'form': form})


def personal_request(request):
    personal_ride_list = RequestRide.objects.all().filter(user=request.user)
    args = {'personal_ride_list': personal_ride_list}
    return render(request, 'user_ride_request_detail.html', args)


def driver_search(request):
    available_ride_list = RequestRide.objects.all()
    ride_dict = {'search_ride': available_ride_list}
    return render(request,'driver_search.html',ride_dict)

def delete_view(request,part_id =None):
    object = RequestRide.objects.get(id=part_id)
    object.delete()
    return HttpResponseRedirect(reverse('rideRequest:personalrequest'))

def accept_view(request,part_id =None):
    object = RequestRide.objects.get(id=part_id)
    object.status_confirm = True
    object.driver_name = request.user.username
    object.driver_vehicle_type = request.user.driver.type
    object.remaining_seat = request.user.driver.max_num_passengers - object.num_passengers
    object.save()
    subject = 'Confirmation'
    message = 'Thank you for your order'
    from_email = settings.EMAIL_HOST_USER
    to_list = [object.user.email]
    send_mail(subject, message, from_email, to_list, fail_silently=True)
    #return HttpResponse(object.remaining_seat)
    return HttpResponseRedirect(reverse('rideRequest:driversearch'))

def complete_view(request,part_id =None):
    object = RequestRide.objects.get(id=part_id)
    #return HttpResponse('hhhhhh')
    object.delete()
    return HttpResponseRedirect(reverse('rideRequest:driversearch'))

def share_view(request):
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = RequestForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            destination = form.cleaned_data['destination']
            date_time = form.cleaned_data['date_time']
            num_passengers = form.cleaned_data['num_passengers']
            type = form.cleaned_data['type']
            special_requests = form.cleaned_data['special_requests']
            share_list = RequestRide.objects.all().filter(destination=destination, date_time=date_time,
                                                        special_requests=special_requests,status_share=True)

            args = []

            if type != '4':
                share_list = share_list.filter(type=type)

            for object in share_list:
                if object.remaining_seat >= num_passengers:
                    args.append(object)
            context_dict = {'eligible_share': args,'num_passengers':num_passengers}

            return render(request,'share_ride.html',context_dict)

    # if a GET (or any other method) we'll create a blank form
    else:
        form = RequestForm()

    return render(request, 'ride_request_detail.html', {'form': form})

def join_view(request,part_id =None,num_passengers=None):
    object = RequestRide.objects.get(id=part_id)

    #if(len(RequestRide.objects.filter(join_list__contains=[request.user.username]))>0):
    #    return render(request, 'ride_request_warning.html')
    
    object.remaining_seat = object.remaining_seat - int(num_passengers)
    object.join_list.append(request.user.username)
    object.save()
    return HttpResponseRedirect(reverse('rideRequest:personalrequest'))

def edit_view(request, part_id =None):
    object = RequestRide.objects.get(id=part_id)
    if request.method == 'POST':
        form = RequestForm(request.POST)

        if form.is_valid():
            object.destination = form.cleaned_data['destination']
            object.date_time = form.cleaned_data['date_time']
            object.num_passengers = form.cleaned_data['num_passengers']
            object.type = form.cleaned_data['type']
            object.special_requests = form.cleaned_data['special_requests']
            object.status_share = form.cleaned_data['status_share']
            object.save()
            return HttpResponseRedirect(reverse('rideRequest:personalrequest'))

    else:
        default_data = {'destination': object.destination, 'date_time': object.date_time,
                        'num_passengers': object.num_passengers, 'type': object.type,
                        'special_requests': object.special_requests, 'status_share':object.status_share}
        form = RequestForm(default_data,instance=request.user)
        args = {'form': form}
        return render(request, 'ride_request_detail.html',args)


def confirmed_view(request):
    confirmed_rider_list = RequestRide.objects.all().filter(driver_name=request.user.username, status_confirm=True)
    ride_dict = {'search_ride': confirmed_rider_list}
    return render(request,'confirmed_ride.html',ride_dict)

docker-deploy/docker-deploy/web-app/rideRequest/templates/rideRequest/confirmed_ride.html
{% extends 'base.html' %}

{% block content %}
<h1>Search Result(Driver)</h1>
<div class="container">
  {% for record in search_ride %}
    <p>User: {{ user.username }}</p>
    <p>Destination: {{ record.destination }}</p>
    <p>Date: {{ record.date_time}}</p>
    <p>Number of passengers: {{ record.num_passengers }}</p>
    <p>Type: {{ record.type }}</p>
    <p>Special : {{ record.special_requests }}</p>
    <p>Share or not: {{ record.status_share }}</p>
    {% if user.driver.max_num_passengers >= record.num_passengers and record.status_confirm == False and user != record.user %}
      {% if user.driver.type == record.type or record.type == '4' %}
        <a href="{% url 'rideRequest:accept_view' record.id %}">Accept</a>
      {% endif %}
    {% else %}
      {% if user.username == record.driver_name %}
        <a href="{% url 'rideRequest:complete_view' record.id %}">Complete!</a>
        {% endif %}
      <h4>Either your car's condition does not meet the requirements or order has beed accepted</h4>
      {% endif %}
  {% endfor %}
</div>

{% endblock %}

docker-deploy/docker-deploy/web-app/rideRequest/templates/rideRequest/driver_search.html
{% extends 'base.html' %}

{% block content %}
<h1>Search Result(Driver)</h1>
<div class="container">
  {% for record in search_ride %}
    <p>User: {{ record.user }}</p>
    <p>Destination: {{ record.destination }}</p>
    <p>Date: {{ record.date_time}}</p>
    <p>Number of passengers: {{ record.num_passengers }}</p>
    <p>Type: {{ record.type }}</p>
    <p>Special : {{ record.special_requests }}</p>
    <p>Share or not: {{ record.status_share }}</p>
    {% if user.driver.max_num_passengers >= record.num_passengers and record.status_confirm == False and user != record.user %}
      {% if user.driver.type == record.type or record.type == '4' %}
        <a href="{% url 'rideRequest:accept_view' record.id %}">Accept</a>
      {% endif %}
    {% else %}
      {% if user.username == record.driver_name %}
        <a href="{% url 'rideRequest:complete_view' record.id %}">Complete!</a>
      {% endif %}
    <h4>Either your car's condition does not meet the requirements or order has beed accepted</h4>
    {% endif %}
  {% endfor %}
</div>

{% endblock %}

docker-deploy/docker-deploy/web-app/rideRequest/templates/rideRequest/ride_request_detail.html
{% extends 'base.html' %}

{% block content %}
<h1>Request a ride</h1>
<div class="container">
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class='btn btn-default' value="Submit">
  </form>
</div>

{% endblock %}

docker-deploy/docker-deploy/web-app/rideRequest/templates/rideRequest/ride_request_warning.html
{% extends 'base.html' %}

{% block content %}
<h1>You have already joined this ride!</h1>

{% endblock %}

docker-deploy/docker-deploy/web-app/rideRequest/templates/rideRequest/share_ride.html
{% extends 'base.html' %}

{% block content %}
<h1>Share List</h1>
<div class="container">
  {% for record in eligible_share %}
    <p>ID: {{ record.id }}</p>
    <p>Destination: {{ record.destination }}</p>
    <p>Date: {{ record.date_time}}</p>
    <p>Number of passengers: {{ record.num_passengers }}</p>
    <p>Type: {{ record.type }}</p>
    <p>Special : {{ record.special_requests }}</p>
    <p>Share or not: {{ record.status_share }}</p>
    <a href="{% url 'rideRequest:join_view' record.id num_passengers%}">Join!</a>
  {% endfor %}
</div>

{% endblock %}

docker-deploy/docker-deploy/web-app/rideRequest/templates/rideRequest/user_ride_request_detail.html
{% extends 'base.html' %}

{% block content %}
<h1>Your Request Detail</h1>
<div class="container">
  {% for record in personal_ride_list %}
    <p>ID: {{ record.id }}</p>
    <p>Destination: {{ record.destination }}</p>
    <p>Date: {{ record.date_time}}</p>
    <p>Number of passengers: {{ record.num_passengers }}</p>
    <p>Type: {{ record.type }}</p>
    <p>Special : {{ record.special_requests }}</p>
    <p>Share or not: {{ record.status_share }}</p>
    {% if record.status_confirm == False %}
      <a href="{% url 'rideRequest:delete_view' record.id %}">Delete</a>
      <a href="{% url 'rideRequest:edit_view' record.id %}">Edit</a>
    {% else %}
      <h4>Driver username: {{ record.driver_name }}</h4>
      <h4>Type: {{ record.driver_vehicle_type }}</h4>
      {% if record.status_share == True %}
        <h4>Who is joining: </h4>
        {% for sharer in record.join_list %}
          <h5>{{ sharer }}</h5>
        {% endfor %}
      {% endif %}
    {% endif %}
  {% endfor %}
</div>

{% endblock %}