docker-deploy/docker-deploy/web-app/driverRegister/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views
from django import forms
from django.forms import ModelForm

app_name = 'driverRegister'

urlpatterns = [
    url(r'^$',views.reg_driver,name='registerdriver'),
    url(r'^profile/$',views.view_profile, name='view_profile'),
    url(r'^profile/edit/$',views.edit_profile, name='edit_profile'),
    url(r'^profile/edit/personal/$',views.edit_profile_personal, name='edit_profile_personal')
]

docker-deploy/docker-deploy/web-app/rideRequest/urls.py
from django.conf.urls import url
from . import views

app_name = 'rideRequest'

urlpatterns = [
    url(r'^$',views.request_ride,name='requestride'),
    url(r'^personalrequest/$',views.personal_request,name='personalrequest'),
    url(r'^driversearch/$',views.driver_search,name='driversearch'),
    url(r'^delete/(?P<part_id>[0-9]+)/$', views.delete_view, name='delete_view'),
    url(r'^accept/(?P<part_id>[0-9]+)/$', views.accept_view, name='accept_view'),
    url(r'^complete/(?P<part_id>[0-9]+)/$', views.complete_view, name='complete_view'),
    url(r'^join/(?P<part_id>[0-9]+)/(?P<num_passengers>[0-9]+)$', views.join_view, name='join_view'),
    url(r'^rideshare/$',views.share_view,name='share_view'),
    url(r'^editride/(?P<part_id>[0-9]+)/$', views.edit_view, name='edit_view'),
    url(r'^confirmedride/$', views.confirmed_view, name='confirmed_view'),
]

docker-deploy/docker-deploy/web-app/ride_share_service/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.HomePage.as_view(),name='home'),
    url(r'^accounts/', include('accounts.urls',namespace='accounts')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^test/$',views.TestPage.as_view(),name='test'),
    url(r'^thanks/$',views.ThanksPage.as_view(),name='thanks'),
    url(r'^registerdriver/', include('driverRegister.urls',namespace='driverregister')),
    url(r'^requestride/', include('rideRequest.urls'))
]

docker-deploy/docker-deploy/web-app/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.HomePage.as_view(),name='home'),
    url(r'^accounts/', include('accounts.urls',namespace='accounts')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^test/$',views.TestPage.as_view(),name='test'),
    url(r'^thanks/$',views.ThanksPage.as_view(),name='thanks'),
    url(r'^registerdriver/', include('driverRegister.urls',namespace='driverregister')),
    url(r'^requestride/', include('rideRequest.urls'))
]

docker-deploy/docker-deploy/web-app/driverRegister/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
User = get_user_model()
# Create your models here.

class Driver(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,null=True)
    #user = models.ForeignKey(User, on_delete=models.CASCADE,)
    TYPE_CHOICES = (
    ('1', 'Type1'),
    ('2', 'Type2'),
    ('3', 'Type3'),
    )
    #name = models.CharField(max_length=264)
    type = models.CharField(max_length=1,choices=TYPE_CHOICES,default='1')
    license_plate_num = models.CharField(max_length=264, default='default value')
    max_num_passengers = models.IntegerField(validators=[MinValueValidator(1),
                                       MaxValueValidator(5)])

    def __str__(self):
        return self.type

docker-deploy/docker-deploy/web-app/driverRegister/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User
from driverRegister.models import Driver
from django.contrib.auth.forms import UserChangeForm

class DriverRegisterForm(forms.ModelForm):
    #first_name = forms.CharField(max_length=None)
    #last_name = forms.CharField(max_length=None)
    class Meta:
        model = Driver
        fields = ['type','license_plate_num','max_num_passengers']

    def save(self, commit=True):
        user = super(DriverRegisterForm,self).save(commit=False)
        #user.first_name = self.cleaned_data['first_name']
        #user.last_name = self.cleaned_data['last_name']
        user.type = self.cleaned_data['type']
        user.license_plate_num = self.cleaned_data['license_plate_num']
        user.max_num_passengers = self.cleaned_data['max_num_passengers']

        if commit:
            user.save()

        return user


class EditProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email']

class EditDriverProfileForm(forms.ModelForm):
    class Meta:
        model = Driver
        fields = ['type','license_plate_num','max_num_passengers']

docker-deploy/docker-deploy/web-app/driverRegister/views.py
from django.shortcuts import render, get_object_or_404
#from django.urls import reverse_lazy
#from django.views.generic import TemplateView
from django.http import HttpResponse, HttpResponseRedirect
from django import forms
from django.forms import ModelForm
from driverRegister.forms import DriverRegisterForm, EditProfileForm, EditDriverProfileForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.decorators import login_required
from django.urls import reverse

# Create your views here.
def reg_driver(request):
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = DriverRegisterForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            instance.save()
            # redirect to a new URL:
            return HttpResponseRedirect('/test/')
            #return render(request, 'driver_register_form.html', {'form': form,'registered': registered})

    # if a GET (or any other method) we'll create a blank form
    else:
        form = DriverRegisterForm()

    return render(request, 'driver_register_form.html', {'form': form})
                                                         #'registered': registered})
@login_required
def view_profile(request):
    args = {'user':request.user}
    return render(request, 'driver_detail.html',args)

@login_required
def edit_profile_personal(request):
    user=request.user
    if request.method == 'POST':
        form = EditProfileForm(request.POST)

        if form.is_valid():
            user.email = form.cleaned_data['email']
            user.save()
            return HttpResponseRedirect(reverse('driverRegister:view_profile'))

    else:
            form = EditProfileForm(instance=request.user)
            args = {'form': form}
            return render(request, 'edit_profile_personal.html',args)

@login_required
def edit_profile(request):
    user=request.user
    #user = get_object_or_404(User, pk=pk)
    if request.method == 'POST':
        form = EditProfileForm(request.POST)
        driver_form = EditDriverProfileForm(request.POST, instance=request.user)

        if form.is_valid() and driver_form.is_valid():
            user.email = form.cleaned_data['email']
            user.driver.type = driver_form.cleaned_data['type']
            user.driver.license_plate_num = driver_form.cleaned_data['license_plate_num']
            user.driver.max_num_passengers = driver_form.cleaned_data['max_num_passengers']

            user.save()
            user.driver.save()
            #form_instance.user = request.user
            #form_instance.save()
            #driver_instance = driver_form.save(commit=False)
            #driver_instance.user = request.user
            #driver_instance.save()

            #return redirect('/driverRegister/profile')
            #return HttpResponseRedirect(reverse('driverRegister:view_profile'))
            #return HttpResponseRedirect('profile/')
            #return redirect('registerdriver/profile')
            return HttpResponseRedirect(reverse('driverRegister:view_profile'))

    else:
        default_data = {'type': user.driver.type, 'license_plate_num': user.driver.license_plate_num,
                        'max_num_passengers': user.driver.max_num_passengers, }
        form = EditProfileForm(instance=request.user)
        driver_form = EditDriverProfileForm(default_data,instance=request.user)
        args = {'form': form, 'driver_form': driver_form}
        return render(request, 'edit_profile.html',args)

docker-deploy/docker-deploy/web-app/driverRegister/templates/driverRegister/driver_detail.html
{% extends 'base.html' %}

{% block head %}
<title>Profile</title>
{% endblock %}

{% block content %}
<div class="container">
  <h1>Profile</h1>
  <p>Username: {{ user }}</p>
  <p>First name: {{ user.first_name }}</p>
  <p>Last name: {{ user.last_name }}</p>
  <p>Email: {{ user.email }}</p>
  {% if not user.driver %}
    <a href="{% url 'driverRegister:edit_profile_personal' %}">Edit file</a>
  {% endif %}
  {% if user.driver.max_num_passengers > 0 %}
    <p>Vehicle Type: {{ user.driver.type }}</p>
    <p>License PLate Number: {{ user.driver.license_plate_num }}</p>
    <p>Maximum Passenger allowed: {{ user.driver.max_num_passengers }}</p>
    <a href="{% url 'driverRegister:edit_profile' %}">Edit file</a>
  {% endif %}
</div>

{% endblock %}

docker-deploy/docker-deploy/web-app/driverRegister/templates/driverRegister/driver_register_form.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <!--{{ registered }}-->
  {% if user.driver.max_num_passengers > 0 %}
    <h1>You have already registered as a driver</h1>
    <li><a href="{% url 'rideRequest:driversearch' %}">Begin Search!</a></li>
  {% else %}
    <h1>Driver Register</h1>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" class='btn btn-default' value="Driver Register">
    </form>
    {% endif %}
  </div>
{% endblock %}

docker-deploy/docker-deploy/web-app/driverRegister/templates/driverRegister/edit_profile.html
{% extends 'base.html' %}

{% block head %}
<title>Edit Profile</title>
{% endblock %}

{% block content %}
<h1>Edit Your Profile</h1>
<div class="container">
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    {{ driver_form.as_p }}
    <input type="submit" class='btn btn-default' value="Submit">
  </form>
</div>

{% endblock %}

docker-deploy/docker-deploy/web-app/driverRegister/templates/driverRegister/edit_profile_personal.html
{% extends 'base.html' %}

{% block head %}
<title>Edit Profile</title>
{% endblock %}

{% block content %}
<h1>Edit Your Profile</h1>
<div class="container">
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class='btn btn-default' value="Submit">
  </form>
</div>

{% endblock %}